export const SCDB_CFOP_ALGS = {
  "F2L": [
    "U R U' R'",
    "R' F R F'",
    "y' r' U' R U M'",
    "y U F' L F L2 U L",
    "F' r U r'",
    "d R U' R'",
    "F' L F L'",
    "y' U R U' R'",
    "U L U' L'",
    "U2 L U2 L'",
    "L' f U f'",
    "U' r U B' U' B r'",
    "U f R' f'",
    "r' U' R U M'",
    "U2 R2 F R F' R",
    "d L U' L'",
    "F R' F' R",
    "y' U' R' U R",
    "U' F' U F",
    "y U' L' U L",
    "U' L' U L",
    "L F' L' F",
    "r U' r' F",
    "U r' U' F U F' r",
    "U' f' L f",
    "l U L' U' M'",
    "d' R' U R",
    "y' U' L' U L",
    "U' R' U R",
    "R f' U' f",
    "U2 R' U2 R",
    "U R' F' U F U' R",
    "F' U' F",
    "y' R' U' R",
    "y L' U' L",
    "S U R U' R' S'",
    "L' U' L",
    "U2 R' F R U R' F' R",
    "y' S U R U' R' S'",
    "U S' F U' F' U S",
    "y R' U' R",
    "f' L' f",
    "f' r' U z",
    "U' R U B' U' B R'",
    "R' U' R",
    "U2 r' R' F R F' r",
    "U S f R' f' U S'",
    "U f2 F' R' f' U S'",
    "R U R'",
    "y' f R f'",
    "y F U F'",
    "y2 L U L'",
    "F U F'",
    "y L U L'",
    "S' L F' L' f",
    "U' M L' U L U' M'",
    "L U L'",
    "r B r'",
    "U f R U R' U2 f' r x'",
    "y2 R U R'",
    "f R f'",
    "y R U R'",
    "y' L U L'",
    "U' r R2 U R U' M",
    "U' R U R' U2 R U' R'",
    "F2 L' U' L U F2",
    "U' R U R' U' R U2 R'",
    "U' R U R' U R' F R F'",
    "U R' F r U' r' F' R",
    "U2 F R U R' U2 F'",
    "U l' U L U' L' U' l",
    "y' U' R U R' U2 R U' R'",
    "U' L U L' U2 L U' L'",
    "U' L U L' U' L U2 L'",
    "y2 U' R U R' U2 R U' R'",
    "U y' l' U L U' L' U' l",
    "U' R' F R U R' U' F' R",
    "U r' U R U' R' U' r",
    "R2 F' U' F U R2",
    "d' R U R' U2 R U' R'",
    "U' r U' R' U R U r'",
    "y' U R' U' R U2 R' U R",
    "d R' U' R U2 R' U R",
    "U F' U' F U2 F' U F",
    "U L' U' L U2 L' U L",
    "F2 R U R' U' F2",
    "R' F2 R U R' U' F2 U R",
    "U L' U' L U L' U2 L",
    "U r U' r' U' L U F L'",
    "y U R' U' R U R' U2 R",
    "U' l U' L' U L U l'",
    "U L F' L' U' L U F L'",
    "U R' U' R U2 R' U R",
    "U2 R' F' U' F U2 R",
    "y2 U L' U' L U2 L' U L",
    "U' y r U' R' U R U r'",
    "U' R U2 R' U' R U2 R'",
    "M' U' M U2 r U' r'",
    "U' R U2 R' U R' F R F'",
    "U' R U2 R' U2 R U' R'",
    "F U R U2 R' U F'",
    "d' L U2 L' U2 L U' L'",
    "U' F U2 R U' R' U F'",
    "l U2 L2 U' L2 U' l'",
    "U' L U2 L' U2 L U' L'",
    "U' L U2 L' U' L U2 L'",
    "M U' M' U2 l U' l'",
    "r U2 R2 U' R2 U' r'",
    "F R U R2 U' R F'",
    "y' U' L U2 L' U2 L U' L'",
    "y U' R U2 R' U2 R U' R'",
    "d R' U2 R U R' U2 R",
    "r' U2 R2 U R2 U r",
    "y' U R' U2 R U2 R' U R",
    "y U L' U2 L U2 L' U L",
    "U L' U2 L U L' U2 L",
    "U r' F2 r U2 r' F r",
    "U' R' U2 R U R' U R U2 L' U L",
    "U L' U2 L U2 L' U L",
    "l' U2 L2 U L2 U l",
    "y U R' U2 R U R' U2 R",
    "d L' U2 L U2 L' U L",
    "f' L' U' L2 U L' f",
    "U R' U2 R U R' U2 R",
    "U R' U2 R U2 R' U R",
    "U' R U' R' U F' U' F",
    "F R U R' U' F' R U' R'",
    "U' R U' R' d R' U' R",
    "d R' U' R U' R' U' R",
    "U L' U' L U' L' U' L",
    "F2 U R U' R' F2",
    "U2 L' U L U L' U' L",
    "U' F U' F' U L' U' L",
    "y U R' U' R U' R' U' R",
    "U' L U' L' U f' L' f",
    "d L' U' L U' L' U' L",
    "y U2 R' U R U R' U' R",
    "U R' U' R U' R' U' R",
    "R' U R U' R' U' R U2 R' U R",
    "U2 R' U R U R' U' R",
    "U2 r U R' U R' U' R2 U' r'",
    "U' R U R' U R U R'",
    "U2 R U' R' U' R U R'",
    "y' U R' U R U' f R f'",
    "d R' U R d' R U R'",
    "U L' U L U' F U F'",
    "F U' R U R' U2 F'",
    "d' L U L' U L U L'",
    "y' U' R U R' U R U R'",
    "U' L U L' U L U L'",
    "U2 L U' L' U' L U L'",
    "L U' L' U L U L' U2 L U' L'",
    "y2 U' R U R' U R U R'",
    "U R' U R U' f R f'",
    "R2 U' F' U F R2",
    "y U' R U R' U R U R'",
    "d' R U R' U R U R'",
    "U' R U2 R' U F' U' F",
    "y' R U2 R2 U' R2 U' R'",
    "U' R U2 R' d R' U' R",
    "F' U L' U2 L U2 F",
    "L' U L U' L' U L U2 L' U L",
    "L U2 L2 U' L2 U' L'",
    "F U R U' R' U R U' R' U F'",
    "U' F U2 F' U r' F' r",
    "U' L U2 L' U f' L' f",
    "U' L U2 L' d L' U' L",
    "L U2 L' U' l U' l' U2 l U l'",
    "y R U2 R2 U' R2 U' R'",
    "R' U R U' R' U R U2 R' U R",
    "R U2 R2 U' R2 U' R'",
    "R' U R U' R' U R U R' U2 R",
    "d' R U2 R' U F' U' F",
    "R U' R' U R U' R' U2 R U' R'",
    "R' U2 R2 U R2 U R",
    "U R U' R' U' R U R' U' R U R'",
    "R' D' R U2 R' D R2 U R'",
    "U L' U2 L U' F U F'",
    "U L' U2 L d' L U L'",
    "L' U2 L U l' U l U2 l' U' l",
    "y' R' U2 R2 U R2 U R",
    "L' U2 L2 U L2 U L",
    "d L' U2 L U' F U F'",
    "U2 R' U2 R U2 L U L' U2 R' U R",
    "L U' L' U L U' L' U2 L U' L'",
    "U R' U2 R U' f R f'",
    "f R' U R2 U' R2 f'",
    "U R' U2 R d' R U R'",
    "y R U' R' U R U' R' U' R U2 R'",
    "y' U R' U R U' R' U' R",
    "M' U' R U R' U2 R U' r'",
    "d R' U R U' R' U' R",
    "R U' R' U R' F R F' R U' R'",
    "U L' U L U' L' U' L",
    "y' R U' R' U2 R U' R' U F' U F",
    "U L' U L U' L' U L U L' U L",
    "U L F' L2 U' L U L F L'",
    "d L' U L U' L' U' L",
    "y U R' U R U' R' U' R",
    "U f' L f U' f' L' f",
    "U L U' L F' L2 U' L U F U L'",
    "U R' U R U' R' U' R",
    "U R' U R U' R' U R U R' U R",
    "U' R U' R' U R U R'",
    "R U2 R' U2 R U R' U2 R U' R'",
    "U' R2 D R' U R D' R2",
    "U2 R2 U R' U R U2 R2",
    "d' L U' L' U L U L'",
    "y U' L U' L' U L U L'",
    "y' U' R U' R' U R U R'",
    "M' U L' U' L U2 L' U l",
    "U' L U' L' U L U L'",
    "U' L U' L' U L U' L' U' L U' L'",
    "y U' R U' R' U R U R'",
    "d' R U' R' U R U R'",
    "y' U' L U' L' U L U L'",
    "U' f R' f' U f R f'",
    "R' D' R U' R' D R U R U' R'",
    "M U r U' r' U' M'",
    "R U R' U2 R U' R' U R U' R'",
    "F' U F U2 R U R'",
    "L' U L U2 F U F'",
    "F U2 R U R' U F'",
    "L' U L U2 y L U L'",
    "U L' l U' l' U l U l' U L",
    "L U L' U2 L U' L' U L U' L'",
    "L U2 L' U L U L' U L U' L'",
    "M' U l U' l' U' M",
    "f' L f U2 L U L'",
    "R' U R U2 f R f'",
    "R2 F R F' R U R' U2 R",
    "R' U R U' d' R U R'",
    "R2 F R F' R U2 R' U R",
    "R U' R' U2 F' U' F",
    "R U' R' U2 y' R' U' R",
    "U M' U R U' r' U' R U R'",
    "U F U R U' R' F' R U R'",
    "F U' R U' R' U2 F'",
    "L' U' L U2 L' U L U' L' U L",
    "L' U2 L U' L' U' L U' L' U L",
    "M U' l' U l U M'",
    "L U' L' U2 f' L' f",
    "L2 F' L' F L' U2 L U' L'",
    "L U' L' y U2 R' U' R",
    "L U' L' U' d' R' U' R",
    "R' U' R U2 R' U R U' R' U R",
    "M' U' r' U r U M",
    "U2 R' U' R U R D R' U' R D' R'",
    "F R' F' R U2 R' U' R2 U' R'",
    "R U2 R' U' R U R'",
    "y2 L U2 L' U' L U L'",
    "R U R' U' R U2 R' U2 R U R'",
    "y L F' L' F L' U L U' L' U L",
    "y L U2 L' U' L U L'",
    "L F' L' F L' U L U' L' U L",
    "L' U2 L U2 l' U L U' L' U' l",
    "y' R U2 R' U' R U R'",
    "L U2 L' U' L U L'",
    "L U L' U' L U2 L' U2 L U L'",
    "y' L U2 L' U' L U L'",
    "y R U2 R' U' R U R'",
    "R' U2 F R U R' U' F' R",
    "l U' R' U l' U R U' R' U R",
    "y' R' U2 R U R' U' R",
    "y L' U2 L U L' U' L",
    "F' U2 F U F' U' F",
    "R' F R F' R U' R' U R U' R'",
    "L' U2 L U L' U' L",
    "y R' U2 R U R' U' R",
    "U F U R U' R' F' L U L'",
    "L U2 F' L' U' L U F L'",
    "L U2 L' U2 l U' L' U L U l'",
    "R' U2 R U R' U' R",
    "U R U2 R' U R U' R'",
    "U R U2 R2 F R F'",
    "d f R2 f' U f R' f'",
    "R U' R' U R U' R' U R U R'",
    "U L' U L2 F' L' F L' U L",
    "d R U2 R' U R U' R'",
    "y' U R U2 R' U R U' R'",
    "y U L U2 L' U L U' L'",
    "U L U2 L' U L U' L'",
    "L U' L' U L U' L' U L U L'",
    "y U R U2 R' U R U' R'",
    "U R' F' U2 F R U R' U' R",
    "U2 f R2 U R2 U' R f'",
    "U2 F' U' F R' U' R S R S'",
    "y' U' R' U2 R U' R' U R",
    "U' R U' R2 F R F' R U' R'",
    "y U' L' U2 L U' L' U L",
    "U' F' U2 F U' F' U F",
    "U' L' U2 L U' L' U L",
    "L' U L U' L' U L U' L' U' L",
    "U' L' U2 L2 F' L' F",
    "y U' R' U2 R U' R' U R",
    "U' L F U2 F' L' U' L U L'",
    "d' R' U2 R U' R' U R",
    "U' L U L' U l U' l' U2 l U l'",
    "U' R' U2 R U' R' U R",
    "R' U R U' R' U R U' R' U' R",
    "U2 R U R' U R U' R'",
    "R U' R' U2 R U R'",
    "R B U2 B' R'",
    "y' f R' f' U2 f R f'",
    "l' U l U2 l' U' l",
    "F R U2 R' F'",
    "y U2 L U L' U L U' L'",
    "y L U' L' U2 L U L'",
    "L U' L' U2 L U L'",
    "U2 L U L' U L U' L'",
    "l U' L' U2 L U l'",
    "L F U2 F' L'",
    "r' U r U2 r' U' r",
    "y' U2 L U L' U L U' L'",
    "U2 R' U' R S R f' U' F",
    "U f U R U' R f'",
    "r U' r' U2 r U r'",
    "F' L' U2 L F",
    "y' U2 R' U' R U' R' U R",
    "y U2 L' U' L U' L' U L",
    "L' U L U2 L' U' L",
    "U2 L' U' L U' L' U L",
    "r' U' F2 U r",
    "U' L' U L U2 L' U L U' L' U L",
    "l U' l' U2 l U l'",
    "f' U' L2 U f",
    "y R' U R U2 R' U' R",
    "y U2 R' U' R U' R' U R",
    "R' U R U2 R' U' R",
    "U2 R' U' R U' R' U R",
    "R' F' U2 F R",
    "U' R' U R U2 R' U R U' R' U R",
    "U R U' R' U' R U' R' U R U' R'",
    "R U R' U2 R U R' U' R U R'",
    "U2 R2 U2 R' U' R U' R2",
    "R U' R2 D' R U2 R' D R",
    "F' U' L' U L F L' U L",
    "F U' R U R' U R U2 R' F'",
    "U L' U' L2 F' L' F L' U L",
    "U' F R U' R' F' L' U' L",
    "U L U' L' U' L U' L' U L U' L'",
    "L U L' U2 L U L' U' L U L'",
    "L' U' L U' L' U2 L2 U2 L'",
    "U2 L2 U2 L' U' L U' L2",
    "U R' F R' F' R2 U' R' U R",
    "U2 l' U' L U' L' U2 B' l",
    "R' F' U' F U2 R U' R' U' R",
    "U R' U' F' U F R U' R' U R",
    "F U R U' R' F' R U' R'",
    "y' R' U' R U2 R' U' R U R' U' R",
    "U' R U R2 F R F' R U' R'",
    "y U' L' U L U L' U L U' L' U L",
    "U' L' U L U L' U L U' L' U L",
    "U' F' r U r' U' L' U' L",
    "L' U L U L' U' L U2 L' U' L",
    "F U' R U2 R' U R U2 R' F'",
    "U2 r U R' U R U2 B r'",
    "U2 F U R U' R' F' U2 L U' L'",
    "y U' R' U R U R' U R U' R' U R",
    "U2 F U R U' R' F' U' L U2 L'",
    "R' U' R U2 R' U' R U R' U' R",
    "U2 R2 U2 R U R' U R2",
    "U' R' U R U R' U R U' R' U R",
    "R U R' U R U2 R2 U2 R",
    "U' R' F R F' R U R'",
    "R' F' R U R U' R' F",
    "U' F' R U R' U' R' F R",
    "U' F' U F U R U' R'",
    "U' L' U L F' r U r'",
    "U' L' U L d R U' R'",
    "U' L' U L F' L F L'",
    "U' L' U L y U L U' L'",
    "L U' L' U' L U' L' U L U L'",
    "R D' R' U' R D R' L U L'",
    "U' f' L' f U L U L'",
    "L' U' L' U' L' U L U L",
    "U' R' U M U' R U M'",
    "R' S' R U' R' S R",
    "U' R' U R r' U' R U M'",
    "d' R' F R F' R U R'",
    "U R U' R' F R' F' R",
    "R S' R' U R S R'",
    "U R U R' U' y L' U' L",
    "U R U' R' U' F' U F",
    "r U r' U' r' F r F'",
    "U L F' L' F L' U' L",
    "U F L' U' L U L F' L'",
    "U F r' F' r U r U' r'",
    "L S L' U L S' L'",
    "F R2 u R u' R2 F'",
    "U L U' M U L' U' M'",
    "U' R u R' U R U' u' R'",
    "U f R f' U' R' U' R",
    "R' U R U R' U R U' R' U' R",
    "R U R U R U' R' U' R'",
    "U' R S2 R' U' R S2 R'",
    "R U' R' U R U' R'",
    "F' U' F U2 R U' R'",
    "y' f R' f' U f R' f'",
    "y' f R' f' r' U' R U M'",
    "L' U' L U F' r U r'",
    "L' U' L U F' L F L'",
    "y' R U' R' U R U' R'",
    "U' F R U2 R' U F'",
    "L U' L' U L U' L'",
    "R' U2 R' F R F' R",
    "R' U' R U r' U' R U M'",
    "y R U' R' U R U' R'",
    "R' U' R U f' U f R'",
    "R U R' U' F R' F' R",
    "y L' U L U' L' U L",
    "F' U F U' F' U F",
    "y' R' U R U' R' U R",
    "L' U L U' L' U L",
    "L' U L2 F' L' F",
    "L U2 L F' L' F L'",
    "y R' U R U' R' U R",
    "L U L' U' l U L' U' M'",
    "L U2 L' U f' L f",
    "R' U R U' R' U R",
    "R' F R F' U R U' R'",
    "y L' U' L U L' U' L",
    "y' R' U' R U R' U' R",
    "R' F R F' R' F R F'",
    "L' U' L U L' U' L",
    "U L' U2 L U2 L' U' L",
    "U F' L F L2 U' L",
    "F' L F L' F' L F L'",
    "y R' U' R U R' U' R",
    "U2 L U' L' f' L' f",
    "f' L' f U f' L' f",
    "x' U' F' U F U' F' U x",
    "R' U' R U R' U' R",
    "U R' U2 R U2 R' U' R",
    "U f' U f R2 U' R",
    "R U R' U' R U R'",
    "U' R U2 R' U2 R U R'",
    "U' F R' F' R2 U R'",
    "U2 F' U F R U R'",
    "L F' L' F U' L' U L",
    "y' R U R' U' R U R'",
    "U' F U' R U2 R' F'",
    "y L U L' U' L U L'",
    "L U L' U' L U L'",
    "U' L U2 L' U2 L U L'",
    "y' L U L' U' L U L'",
    "f R f' U' f R f'",
    "U2 R' U R f R f'",
    "y R U R' U' R U R'",
    "U' R' F R F' R U' R'",
    "R U' R' U y' R' U R",
    "F' U F R U2 R'",
    "R U' R' U y L' U L",
    "U L F' L' F L' U L",
    "L' U L U' y L U' L'",
    "L' U L F U2 F'",
    "U' F' L F L' F U' F'",
    "L U' L F' L' F L'",
    "f' L f U' L U' L'",
    "B' U B L U2 L'",
    "L U2 L' U' l U L' U' M'",
    "R' U R' F R F' R",
    "R' U R f R2 f'",
    "R' U R y R U2 R'",
    "f R' f' U R' U R",
    "U R U' R' U R U' R' U R U' R'",
    "R U R' U' R U R' U' R U R'",
    "R2 U R2 U R2 U2 R2",
    "U' F R' F' R U' R U R'",
    "U' L' U L U' L' U L U' L' U L",
    "U L' U L U' L' U2 L U L' U' L",
    "U2 F U' R U R' U F'",
    "L' U' L U L' U' L U L' U' L",
    "L U L' U' L U L' U' L U L'",
    "U L U' L' U L U' L' U L U' L'",
    "L2 U L2 U L2 U2 L2",
    "U' L U' L' U L U2 L' U' L U L'",
    "U' R' U R U' R' U R U' R' U R",
    "R' U' R U R' U' R U R' U' R",
    "U2 f R' U R U' R f'",
    "R2 U' R2 U' R2 U2 R2",
    "U' R U' R' U2 R U' R'",
    "y R' D R U' R' D' R",
    "R U R' U' R U' R' U R U' R'",
    "U' R U' R' U' R U2 R'",
    "R' D R U' R' D' R",
    "U L' U2 L U' L' U' L",
    "U' L D L' U L D' L'",
    "U' L' U' L U2 L' U' L",
    "U' L U' L' U2 L U' L'",
    "U' L U' L' U' L U2 L'",
    "D' R D R' U R D' R' D",
    "U' R D R' U R D' R'",
    "U' R' U' R U2 R' U' R",
    "U R' U2 R U' R' U' R",
    "U R D R' U' R D' R'",
    "U R U R' U2 R U R'",
    "U' R U2 R' U R U R'",
    "U R' D' R U' R' D R",
    "y U L' U L U2 L' U L",
    "U L' U L U2 L' U L",
    "U L' U L U L' U2 L",
    "L' U' L U L' U L U' L' U L",
    "U L U L' U2 L U L'",
    "U L' D' L U' L' D L",
    "U' L U2 L' U L U L'",
    "U2 R D' R' U' R D R'",
    "U R' U R U R' U2 R",
    "U f R2 U R2 U' f'",
    "U R2 F R F' R U' R' U R",
    "U R' U R U2 R' U R",
    "U' R U R' U F' U' F",
    "U' R U R' d R' U' R",
    "U2 R U R' F R' F' R",
    "U2 R U R' y' U' R' U R",
    "U2 F U F' U' L' U L",
    "U' F R' F R F' U F'",
    "U2 L F' L' F U2 L' U' L",
    "U' F U F' U L' U' L",
    "U' L U L' U f' L' f",
    "U2 L U L' U' L F U F' L'",
    "L U L' y R' U' R U R' U' R",
    "U2 L U M U L' U' M'",
    "U' f R f' U R' U' R",
    "R' F R' F' R U R U' R' U' R",
    "U2 f R f' U' R' U R",
    "U' R' F' U F U' R U R' U' R",
    "U F' U' F U' R U R'",
    "U2 R' F R F' U2 R U R'",
    "R2 u R U R' U' u' R' U R'",
    "R U R' U R U R' U' F' U' F",
    "U L' U' L d' L U L'",
    "U2 L' U' L F' L F L'",
    "U L' U' L U' F U F'",
    "U2 L' U L U F U F'",
    "U f' L' f U' L U L'",
    "U2 f' L' f U L U' L'",
    "L F' L F L' U' L' U L U L'",
    "y U R' U' R U' f R f'",
    "U R' U' R U' f R f'",
    "U2 R' U' R U R' F' U' F R",
    "U R' U' R y U' R U R'",
    "U R' U' R U' y R U R'",
    "R2 U2 F R2 F' U2 R' U R'",
    "R' F R F' R U' R' U R U' R' U2 R U' R'",
    "R U2 R' U R U2 R' U F' U' F",
    "R U R' U2 R U2 R' U y' R' U' R",
    "L2 U2 F' L2 F U2 L U' L",
    "L' U2 L U' L' U2 L U' F U F'",
    "L' U' L U2 L' U2 L U' y' R U R'",
    "R' F R L' U' L U' R' F R L' U' L",
    "L U' L' l' U2 L2 U L2 U l",
    "f' L f U' L U2 L' U2 L U' L'",
    "L U2 L' U L U2 L' U f' L' f",
    "L' f U f' L' U2 L2 U L2 U L",
    "R' U R r U2 R2 U' R2 U' r'",
    "R' U2 R U' R' U2 R U' f R f'",
    "R' U R f R U R2 U' R f'",
    "R' U' R U2 R' U2 R U' f R f'",
    "R U' R' U' R U R' U2 R U' R'",
    "R U R' U' R U2 R' U' R U R'",
    "R2 U2 R' U' R U' R' U2 R'",
    "R U' R' U' R U R' U' R U2 R'",
    "L' U L U' L' U2 L U' L' U L",
    "F R U2 R' U' R U R' U2 F'",
    "L' U2 L' U' L U' L' U2 L2",
    "F U' R U2 R' U' R U2 R' F'",
    "L U L' U' L U2 L' U' L U L'",
    "L2 U2 L' U' L U' L' U2 L'",
    "L U' L' U' L U L' U' L U2 L'",
    "L U' L' U' L U L' U2 L U' L'",
    "R' U' R U2 R' U R U' R' U' R",
    "R' U R U' R' U2 R U' R' U R",
    "R' U2 R' U' R U' R' U2 R2",
    "R U' R' U R U2 R' U R U' R'",
    "R U2 R U R' U R U2 R2",
    "R U R' U2 R U' R' U R U R'",
    "R U2 R' U R U' R' U R U R'",
    "L' U' L U L' U2 L U L' U' L",
    "F' L F L2 U2 L U L' U' L",
    "F U2 R U' R' U R U2 R' F'",
    "L' U L U L' U' L U2 L' U L",
    "L U L' U2 L U' L' U L U L'",
    "L U' L' U L U2 L' U L U' L'",
    "L U2 L' U L U' L' U L U L'",
    "L U2 L U L' U L U2 L2",
    "R' U' R U R' U2 R U R' U' R",
    "R' U R U R' U' R U2 R' U R",
    "f R2 U R' U' F R' f' U F'",
    "R2 U2 R U R' U R U2 R",
    "r U' r' U2 r U r' R U R'",
    "F' L' U2 L F R U R'",
    "R U' R' F R U R' U' F' R U' R'",
    "R U' R' U' R U' R' U y' R' U' R",
    "L' U L F R U2 R' F'",
    "L' U L l' U l U2 l' U' l",
    "L' U L R' F R U2 R' F' R",
    "L' U L U2 y L U L' U L U' L'",
    "l U' l' U2 l U l' L U L'",
    "f' L f U2 L U L' U L U' L'",
    "f' L f U2 L U L' U2 L U2 L'",
    "f' L f L F U2 F' L'",
    "R' U R r' U r U2 r' U' r",
    "R' U R f U R2 U' f'",
    "R2 F' U' F U R U' R",
    "R' F' U2 F R f R f'",
    "R U' R' r U' r' U2 r U r'",
    "R U' R' F' L' U2 L F",
    "R U R' U' y M U' R' F R U M'",
    "R U R' U' R U' R' U2 y' R' U' R",
    "l' U l U2 l' U' l L' U' L",
    "L' U L U L' U L U' y' R U R'",
    "F R U2 R' F' L' U' L",
    "R' F R U2 R' F' R L' U' L",
    "f' L f U' L U L' U L U L'",
    "L2 F U F' U' L' U L'",
    "L F U2 F' L' f' L' f",
    "L U' L' d' U' R' U' R U' R' U R",
    "r' U r U2 r' U' r R' U' R",
    "R' U R' U' F' U F R2",
    "f R' f' U2 R' U' R U' R' U R",
    "f R' f' U2 R' U' R U2 R' U2 R"
  ],
  "OLL": [
    "R U2 R2 F R F' U2 R' F R F'",
    "y R U' R2 D' r U' r' D R2 U R'",
    "f R U R' U' R f' U' r' U' R U M'",
    "L' U2 L2 F' L' F U2 L F' L' F",
    "y' R U' R2 D' r U r' D R2 U R'",
    "F R U R' U' S R U R' U' f'",
    "F R U R' U' F' f R U R' U' f'",
    "y r U r' U2 R U2 R' U2 r U' r'",
    "y' f R U R' U' f' U' F R U R' U' F'",
    "y R' F2 R2 U2 R' F R U2 R2 F2 R",
    "r' R2 U R' U r U2 r' U M'",
    "M R U R' U r U2 r' U M'",
    "y' R' F2 R2 U2 R' F' R U2 R2 F2 R",
    "y' f R U R' U' f' U F R U R' U' F'",
    "R' F R F' U' S R' U' R U R S'",
    "y F U R U' R' F' U' F R U R' U' F'",
    "r' U2 R U R' U r",
    "y2 l' U2 L U L' U l",
    "y2 R' F2 r U r' F R",
    "y2 R' F2 L F L' F R",
    "r U2 R' U' R U' r'",
    "F U' R2 D R' U' R D' R2 U F'",
    "y2 l U2 L' U' L U' l'",
    "y' x' D R2 U' R' U R' D' x",
    "r U R' U R U2 r'",
    "S' R U R' U R U2 R' U S",
    "L' U2 L U2 L F' L' F",
    "y2 l U L' U L U2 l'",
    "y2 r' U' R U' R' U2 r",
    "l' U' L U' L' U2 l",
    "R U2 R' U2 R' F R F'",
    "R' F' r U' r' F2 R",
    "y R U R' U' R' F R2 U R' U' F'",
    "R U2 R' U' S' R U' R' S",
    "y2 F' U' F r U' r' U r U r'",
    "y' L' U' L U' L F' L' F L' U2 L",
    "R U R' U R' F R F' R U2 R'",
    "y F U F' R' F R U' R' F' R",
    "y M' R' U2 R U R' U R U M",
    "y2 L' U' L U L F' L2 U' L U F",
    "r' R2 U R' U R U2 R' U M'",
    "y2 r U R' U R' F R F' R U2 r'",
    "S R U R' U R U2 R' U2 S'",
    "M R U R' U R U2 R' U M'",
    "y' M' R' U' R U' R' U2 R U' M",
    "F R U R' U' F' U F R U R' U' F'",
    "y' S R' U' R U' R' U2 R U2 S'",
    "y l L2 U' L U' L' U2 L U' M'",
    "F U R U2 R' U' R U R' F'",
    "F U R U' R2 F' R U R U' R'",
    "r U' r' U' r U r' F' U F",
    "r U' r' U' r U r' y L' U L",
    "R' F R U R' F' R F U' F'",
    "r U R' U' r' F R2 U R' U' F'",
    "F' U' L' U L2 F L' U' L' U L",
    "l' U l U l' U' l F U' F'",
    "r' U' r R' U' R U r' U r",
    "y2 l' U' l L' U' L U l' U l",
    "r' U' M' U' R U r' U r",
    "y2 R' F' R L' U' L U R' F R",
    "r U r' R U R' U' r U' r'",
    "r U M U R' U' r U' r'",
    "y2 R' F R U R' U' F' R U' R' U2 R",
    "y2 l U l' L U L' U' l U' l'",
    "R U R' U R' F R F' U2 R' F R F'",
    "y2 F R' F' R U S' R U' R' S",
    "y2 F R' F' R2 r' U R U' R' U' M'",
    "y' F' r U r' U' S r' F r S'",
    "y R U2 R2 F R F' U2 M' U R U' r'",
    "r U R' U R U2 r2 U' R U' R' U2 r",
    "y F S' R U' R' S R U2 R' U' F'",
    "R D r' U' r D' R' U' R2 F R F' R",
    "y S' R U R' S U' R' F R F'",
    "M U R U R' U' M' R' F R F'",
    "R' U2 F R U R' U' F2 U2 F R",
    "r' R U R U R' U' r R2 F R F'",
    "r U R' U' M2 U R U' R' U' M'",
    "M' U2 M U2 M' U M U2 M' U2 M",
    "S' R U R' S U' M' U R U' r'",
    "S R' U' R U R U R U' R' S'",
    "R U R' U R U' R' U R U2 R'",
    "y R U2 R' U' R U R' U' R U' R'",
    "y F R U R' U' R U R' U' R U R' U' F'",
    "R' U' R U' R' U R U' R' U2 R",
    "R U2 R2 U' R2 U' R2 U2 R",
    "R' U2 R2 U R2 U R2 U2 R'",
    "f R U R' U' S' R U R' U' F'",
    "f R U R' U' f' F R U R' U' F'",
    "R2 D R' U2 R D' R' U2 R'",
    "y2 R2 D' R U2 R' D R U2 R",
    "R U R' U R U2 R2 U' R U' R' U2 R",
    "y R U R' U' R U' R' U2 R U' R' U2 R U R'",
    "r U R' U' r' F R F'",
    "y2 R' F' r U R U' r' F",
    "y' x' R U R' D R U' R' D' x",
    "y R U R D R' U' R D' R2",
    "R U2 R D R' U2 R D' R2",
    "y F' r U R' U' r' F R",
    "F R' F' r U R U' r'",
    "x R' U R D' R' U' R D x'",
    "y R U2 R' U' R U' R'",
    "R' U' R U' R' U2 R",
    "y2 L' U' L U' L' U2 L",
    "y2 L' U R U' L U R'",
    "R U R' U R U2 R'",
    "y' R' U2 R U R' U R",
    "y L' U2 L U L' U L",
    "y2 L U L' U L U2 L'",
    "r U R' U' M U R U' R'",
    "R' F R S R' F' R S'",
    "r U R' U' r' R U R U' R'",
    "y2 M' U M U2 M' U M",
    "r2 D' r U r' D r2 U' r' U' r",
    "y R U R' U' R U' R' F' U' F R U R'",
    "y S' R U R' U' R' F R F' U S",
    "M U R U R' U' R' F R F' M'",
    "y' r' D' r U' r' D r2 U' r' U r U r'",
    "y2 F U R U2 R' U' R U2 R' U' F'",
    "y2 F R' F R2 U' R' U' R U R' F2",
    "y S' R' U' R f R' U R U' F'",
    "R' U' F U R U' R' F' R",
    "y2 S' L' U' L U L F' L' f",
    "y S R U R' U' f' U' F",
    "y' F R' F' R U R U R' U' R U' R'",
    "S R U R' U' R' F R f'",
    "y2 L U F' U' L' U L F L'",
    "R U B' U' R' U R B R'",
    "y' R' F R F' U' r U' r' U r U r'",
    "R U R' U' R' F R F'",
    "y2 L' U' L U L F' L' F",
    "y2 r' F' r U r U' r' F",
    "R U R' F' U' F R U' R'",
    "y f R f' U' r' U' R U M'",
    "y2 R U R2 U' R' F R U R U' F'",
    "F R U R' U' R' F' r U R U' r'",
    "y2 R U R' U' B' R' F R F' B",
    "R U2 R2 F R F' R U2 R'",
    "f R U R' U' f' R U R' U R U2 R'",
    "y L' U2 L2 F' L' F L' U2 L",
    "R U2 R' d' R' F R U' R' F' R",
    "y R U R2 F' U' F U R2 U2 R'",
    "y2 L' U' L U' L' U L U L F' L' F",
    "y2 R U R' F' R U R' U' R' F R U' R' F R F'",
    "y2 R' F' U' F2 U R U' R' F' R",
    "F R' F' R U R U' R'",
    "F R U' R' U' R U R' F'",
    "y F' r U r' U' r' F r",
    "y2 r2 D' r U' r' D r U r",
    "R U R' U R U' R' U' R' F R F'",
    "y F R U' R' S U' R U R' f'",
    "r U R' U' r' F R U R U' R' F'",
    "y2 L U L' U L U' L' U' L' B L B'",
    "y' f' r U r' U' r' F r S",
    "y' R U R' F' U' F U R U2 R'",
    "y L F' L' U' L U F U' L'",
    "y' f' L F L' U' L' U L S",
    "y R' F R U R' U' F' U R",
    "y' f R' F' R U R U' R' S'",
    "R r D r' U r D' r' U' R'",
    "y' L' U' L F U F' U' L' U2 L",
    "y2 R U R' U R U2 R' F R U R' U' F'",
    "y2 F U R2 D R' U' R D' R2 F'",
    "y' S U' R' F' U' F U R S'",
    "M U' F' L' U' L U F M'",
    "R' U' R U' R' U2 R F R U R' U' F'",
    "y F S' R U R' U' F' U S",
    "y R' F R F' R' F R F' R U R' U' R U R'",
    "y R' U' F2 u' R U R' D R2 B",
    "y R' U' F' U F R",
    "y2 F' U' L' U L F",
    "f' L' U' L U f",
    "B' U' R' U R B",
    "f R U R' U' f'",
    "y2 F U R U' R' F'",
    "y R U B U' B' R'",
    "y' L U F U' F' L'",
    "F R U R' U' F'",
    "y R' F' U' F U R",
    "y2 f U R U' R' f'",
    "y2 F' L' U' L U F",
    "R' U' R' F R F' U R",
    "R' F' U' F R U' R' U2 R",
    "y F R U R' U' F' U' R U R' U R U2 R'",
    "l' U2 L2 F' L' F U L' U l",
    "y' F R' F' R U2 R U' R' U R U2 R'",
    "F' L' U' L U L' U' L U F",
    "R' U' R' F R F' R' F R F' U R",
    "y' R' F' U' F U F' U' F U R",
    "F R U R' U' R U R' U' F'",
    "y2 f U R U' R' U R U' R' f'",
    "R U2 R' U' R U R' U2 R' F R F'",
    "F R' F' U2 R U R' U R2 U2 R'",
    "y2 r U' r2 U r2 U r2 U' r",
    "l U' l2 U l2 U l2 U' l",
    "R B' R2 F R2 B R2 F' R",
    "y2 R' F R' F' R2 U2 B' R B R'",
    "r' U r2 U' r2 U' r2 U r'",
    "y2 R' F R2 B' R2 F' R2 B R'",
    "y' R U2 R' U' R U' R' F R U R' U' F'",
    "y2 l' U l2 U' l2 U' l2 U l'",
    "y2 F U R U' R' U R U' R' F'",
    "f R U R' U' R U R' U' f'",
    "y' R' U' R' F R F' R U' R' U2 R",
    "y r' F' U' F U F' U' F U r",
    "y2 R' F' U' F U' R U R' U R",
    "R U R' U R U' B U' B' R'",
    "R U R' U R d' R U' R' F'",
    "R U R' U R U' y R U' R' F'",
    "r' U' R U' R' U R U' R' U2 r",
    "y2 l' U' L U' L' U L U' L' U2 l",
    "y r' U2 R U R' U' R U R' U r",
    "y' l' U2 L U L' U' L U L' U l",
    "r U R' U R U' R' U R U2 r'",
    "y' r U2 R' U' R U R' U' R U' r'",
    "y' r U r' R U R' U' R U R' U' r U' r'",
    "y2 l U L' U L U' L' U L U2 l'",
    "y R' F U R U' R2 F' R2 U R' U' R",
    "y R' F R U R U' R2 F' R2 U' R' U R U R'",
    "R U2 R2 U' R U' R' U2 F R F'",
    "r U2 R2 F R F' U2 r' F R F'",
    "r U r' U R U' R' U R U' R' r U' r'",
    "r U r' U R U' R' M' U R U2 r'",
    "F R U R' U' R F' r U R' U' r'",
    "r' U' r U' R' U R U' R' U R r' U r",
    "R U R' U' M' U R U' r'",
    "y R U' R' S' R U R' S",
    "y R U R' S' R U' R' S",
    "R U R' U' R' r U R U' r'"
  ],
  "PLL": [
    "x R' U R' D2 R U' R' D2 R2 x'",
    "y' x L2 D2 L' U' L D2 L' U L'",
    "l' U R' D2 R U' R' D2 R2 x'",
    "y x' R2 D2 R' U' R D2 R' U R' x",
    "x R2 D2 R U R' D2 R U' R x'",
    "y' x L U' L D2 L' U L D2 L2",
    "y x' R U' R D2 R' U R D2 R2 x",
    "R' B' R U' R D R' U R D' R2 B R",
    "y x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    "y R' U' R' D' R U' R' D R U R' D' R U R' D R2",
    "R2 U F' R' U R U' R' U R U' R' U R U' F U' R2",
    "y x' L' U L D' L' U' L D L' U' L D' L' U L D",
    "y R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "y R' F R f' R' F R2 U R' U' R' F' R2 U R' S",
    "R' U R U' R2 F' U' F U R F R' F' R2",
    "y R2 F R F' R' U' F' U F R2 U R' U' R",
    "R2 U R' U R' U' R U' R2 D U' R' U R D'",
    "R2 u R' U R' U' R u' R2 F' U F",
    "y R U R' F' R U R' U' R' F R U' R' F R2 U' R' U' R U R' F'",
    "D' R2 U R' U R' U' R U' R2 U' D R' U R",
    "D R' U' R U D' R2 U R' U R U' R U' R2",
    "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "y F' U' F R2 u R' U R U' R u' R2",
    "R' d' F R2 u R' U R U' R u' R2",
    "R2 U' R U' R U R' U R2 D' U R U' R' D",
    "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2",
    "D R2 U' R U' R U R' U R2 D' U R U' R'",
    "R2 u' R U' R U R' u R2 f R' f'",
    "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    "D' R U R' U' D R2 U' R U' R' U R' U R2",
    "R U R' y' R2 u' R U' R' U R' u R2",
    "y R2 F' R U R U' R' F' R U2 R' U2 R' F2 R2",
    "M2 U' M2 U2 M2 U' M2",
    "M2 U M2 U2 M2 U M2",
    "R2 S2 R2 U' R2 S2 R2",
    "M2 U2 M2 U M2 U2 M2",
    "y2 x R2 F R F' R U2 r' U r U2 x'",
    "y R' U L' U2 R U' R' U2 R L",
    "L' U' L F L' U' L U L F' L2 U L",
    "R U' L' U R' U2 L U' L' U2 L",
    "R U R' F' R U R' U' R' F R2 U' R'",
    "R U2 R' U' R U2 L' U R' U' L",
    "r' F R F' r U2 R' U R U2 R'",
    "L' U R U' L U2 R' U R U2 R'",
    "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "F' R U R' U' R' F R2 F U' R' U' R U F' R'",
    "R F U' R' U R U F' R2 F' R U R U' R' F",
    "r' D r U2 r' D r U2 r' D r U2 r' D r U2 r' D r",
    "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "r' D' F r U' r' F' D r2 U r' U' r' F r F'",
    "R' U L' U2 R U' L R' U L' U2 R U' L",
    "R' U R U' R' F' U' F R U R' U' R U' f R f'",
    "y R U' R' U' R U R D R' U' R D' R' U2 R'",
    "y R U R' F' R U2 R' U2 R' F R U R U2 R'",
    "L U2 L' U2 L F' L' U' L U L F L2",
    "y R U' R' U' R U R' U R' D' R U' R' D R2 U R'",
    "R' U2 R U2 R' F R U R' U' R' F' R2",
    "y R2 F R U R U' R' F' R U2 R' U2 R",
    "R' U2 R' D' R U' R' D R U R U' R' U' R",
    "y R' U R U R' U' R' D' R U R' D R U2 R",
    "R U R' U' R' F R2 U' R' U' R U R' F'",
    "l b d' L' U' F U2 L' U' L' U L U' f' S M r u E U' R'",
    "R U R' U' R' F R2 U' R' U F' L' U L",
    "R2 u R2 u' R2 F2 u' F2 u F2",
    "y2 M2 U M U2 M' U M2",
    "R U R' U R' U' R2 U' R' U R' U R",
    "y R2 U' S' U2 S U' R2",
    "y2 R U' R U R U R U' R' U' R2",
    "y2 M2 U' M U2 M' U' M2",
    "R' U R' U' R' U' R' U R U R2",
    "R2' U R U R' U' R3 U' R' U R'",
    "y2 R2 U R U R' U' R' U' R' U R'",
    "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
    "R' U R U' R' f' U' R U2 R' U' R U' R' f R",
    "y R U' R U R' D R D' R U' D R2 U R2 D' R2",
    "R' U R' U' y R' F' R2 U' R' U R' F R F",
    "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "F R' F R2 U' R' U' R U R' F' R U R' U' F'",
    "R2 U' R2 U' R2 U F U F' R2 F U' F'",
    "F R' F' R U R U' R2 U' R U R f' U' f",
    "M' U' M2 U' M2 U' M' U2 M2",
    "M2 U M2 U M' U2 M2 U2 M'",
    "y M2 U' M2 U' M' U2 M2 U2 M'",
    "y M' U M2 U M2 U M' U2 M2"
  ]
};
